# Generated by Django 5.2.8 on 2025-11-20 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=256)),
                ('image', models.ImageField(default='avatars/default.png', null=True, upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('jobs', models.CharField(blank=True, choices=[('developer', 'Dasturchi'), ('designer', 'Dizayner'), ('teacher', 'O‘qituvchi'), ('doctor', 'Shifokor'), ('engineer', 'Muhandis'), ('driver', 'Haydovchi'), ('businessman', 'Biznesmen'), ('bloger', 'Bloger'), ('accountant', 'Buxgalter'), ('student', 'Talaba')], default='student', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='users.users')),
            ],
        ),
    ]
